# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comparator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63omparator.proto\x12\ncomparator\"=\n\x13ImageCompareRequest\x12\x12\n\nimage1name\x18\x01 \x01(\t\x12\x12\n\nimage2name\x18\x02 \x01(\t\"2\n\x11ImageCompareReply\x12\x1d\n\x15\x63omparison_percentage\x18\x01 \x01(\x02\"N\n\x12RenderImageRequest\x12\x11\n\timageName\x18\x01 \x01(\t\x12\x11\n\timage_css\x18\x02 \x01(\t\x12\x12\n\nimage_html\x18\x03 \x01(\t\">\n\x10RenderImageReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\"#\n\x13\x44\x65liverImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x11\x44\x65liverImageReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x32_\n\nComparator\x12Q\n\rCompareImages\x12\x1f.comparator.ImageCompareRequest\x1a\x1d.comparator.ImageCompareReply\"\x00\x32\xab\x01\n\x08Renderer\x12M\n\x0bRenderImage\x12\x1e.comparator.RenderImageRequest\x1a\x1c.comparator.RenderImageReply\"\x00\x12P\n\x0c\x44\x65liverImage\x12\x1f.comparator.DeliverImageRequest\x1a\x1d.comparator.DeliverImageReply\"\x00\x42.Z,github.com/anirudhRowjee/cssbatt_demux/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comparator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/anirudhRowjee/cssbatt_demux/proto'
  _IMAGECOMPAREREQUEST._serialized_start=32
  _IMAGECOMPAREREQUEST._serialized_end=93
  _IMAGECOMPAREREPLY._serialized_start=95
  _IMAGECOMPAREREPLY._serialized_end=145
  _RENDERIMAGEREQUEST._serialized_start=147
  _RENDERIMAGEREQUEST._serialized_end=225
  _RENDERIMAGEREPLY._serialized_start=227
  _RENDERIMAGEREPLY._serialized_end=289
  _DELIVERIMAGEREQUEST._serialized_start=291
  _DELIVERIMAGEREQUEST._serialized_end=326
  _DELIVERIMAGEREPLY._serialized_start=328
  _DELIVERIMAGEREPLY._serialized_end=376
  _COMPARATOR._serialized_start=378
  _COMPARATOR._serialized_end=473
  _RENDERER._serialized_start=476
  _RENDERER._serialized_end=647
# @@protoc_insertion_point(module_scope)
