// Protobuf Definition for the Gorjus Services

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: comparator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageCompareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image1Name string `protobuf:"bytes,1,opt,name=image1name,proto3" json:"image1name,omitempty"`
	Image2Name string `protobuf:"bytes,2,opt,name=image2name,proto3" json:"image2name,omitempty"`
}

func (x *ImageCompareRequest) Reset() {
	*x = ImageCompareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCompareRequest) ProtoMessage() {}

func (x *ImageCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCompareRequest.ProtoReflect.Descriptor instead.
func (*ImageCompareRequest) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{0}
}

func (x *ImageCompareRequest) GetImage1Name() string {
	if x != nil {
		return x.Image1Name
	}
	return ""
}

func (x *ImageCompareRequest) GetImage2Name() string {
	if x != nil {
		return x.Image2Name
	}
	return ""
}

type ImageCompareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComparisonPercentage float32 `protobuf:"fixed32,1,opt,name=comparison_percentage,json=comparisonPercentage,proto3" json:"comparison_percentage,omitempty"`
}

func (x *ImageCompareReply) Reset() {
	*x = ImageCompareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageCompareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCompareReply) ProtoMessage() {}

func (x *ImageCompareReply) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCompareReply.ProtoReflect.Descriptor instead.
func (*ImageCompareReply) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{1}
}

func (x *ImageCompareReply) GetComparisonPercentage() float32 {
	if x != nil {
		return x.ComparisonPercentage
	}
	return 0
}

type RenderImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageCss  string `protobuf:"bytes,2,opt,name=image_css,json=imageCss,proto3" json:"image_css,omitempty"`
	ImageHtml string `protobuf:"bytes,3,opt,name=image_html,json=imageHtml,proto3" json:"image_html,omitempty"`
}

func (x *RenderImageRequest) Reset() {
	*x = RenderImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderImageRequest) ProtoMessage() {}

func (x *RenderImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderImageRequest.ProtoReflect.Descriptor instead.
func (*RenderImageRequest) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{2}
}

func (x *RenderImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RenderImageRequest) GetImageCss() string {
	if x != nil {
		return x.ImageCss
	}
	return ""
}

func (x *RenderImageRequest) GetImageHtml() string {
	if x != nil {
		return x.ImageHtml
	}
	return ""
}

type RenderImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Image []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *RenderImageReply) Reset() {
	*x = RenderImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderImageReply) ProtoMessage() {}

func (x *RenderImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderImageReply.ProtoReflect.Descriptor instead.
func (*RenderImageReply) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{3}
}

func (x *RenderImageReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenderImageReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RenderImageReply) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type DeliverImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeliverImageRequest) Reset() {
	*x = DeliverImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverImageRequest) ProtoMessage() {}

func (x *DeliverImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverImageRequest.ProtoReflect.Descriptor instead.
func (*DeliverImageRequest) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{4}
}

func (x *DeliverImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeliverImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *DeliverImageReply) Reset() {
	*x = DeliverImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comparator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverImageReply) ProtoMessage() {}

func (x *DeliverImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_comparator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverImageReply.ProtoReflect.Descriptor instead.
func (*DeliverImageReply) Descriptor() ([]byte, []int) {
	return file_comparator_proto_rawDescGZIP(), []int{5}
}

func (x *DeliverImageReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliverImageReply) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_comparator_proto protoreflect.FileDescriptor

var file_comparator_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x55,
	0x0a, 0x13, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x31, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x31, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x32, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x11, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x15, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x69, 0x73, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x22,
	0x6e, 0x0a, 0x12, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x73, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x22,
	0x52, 0x0a, 0x10, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x5f, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x51, 0x0a, 0x0d, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0xab,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x0b, 0x52,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x69, 0x72, 0x75,
	0x64, 0x68, 0x52, 0x6f, 0x77, 0x6a, 0x65, 0x65, 0x2f, 0x63, 0x73, 0x73, 0x62, 0x61, 0x74, 0x74,
	0x5f, 0x64, 0x65, 0x6d, 0x75, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comparator_proto_rawDescOnce sync.Once
	file_comparator_proto_rawDescData = file_comparator_proto_rawDesc
)

func file_comparator_proto_rawDescGZIP() []byte {
	file_comparator_proto_rawDescOnce.Do(func() {
		file_comparator_proto_rawDescData = protoimpl.X.CompressGZIP(file_comparator_proto_rawDescData)
	})
	return file_comparator_proto_rawDescData
}

var file_comparator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_comparator_proto_goTypes = []interface{}{
	(*ImageCompareRequest)(nil), // 0: comparator.ImageCompareRequest
	(*ImageCompareReply)(nil),   // 1: comparator.ImageCompareReply
	(*RenderImageRequest)(nil),  // 2: comparator.RenderImageRequest
	(*RenderImageReply)(nil),    // 3: comparator.RenderImageReply
	(*DeliverImageRequest)(nil), // 4: comparator.DeliverImageRequest
	(*DeliverImageReply)(nil),   // 5: comparator.DeliverImageReply
}
var file_comparator_proto_depIdxs = []int32{
	0, // 0: comparator.Comparator.CompareImages:input_type -> comparator.ImageCompareRequest
	2, // 1: comparator.Renderer.RenderImage:input_type -> comparator.RenderImageRequest
	4, // 2: comparator.Renderer.DeliverImage:input_type -> comparator.DeliverImageRequest
	1, // 3: comparator.Comparator.CompareImages:output_type -> comparator.ImageCompareReply
	3, // 4: comparator.Renderer.RenderImage:output_type -> comparator.RenderImageReply
	5, // 5: comparator.Renderer.DeliverImage:output_type -> comparator.DeliverImageReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comparator_proto_init() }
func file_comparator_proto_init() {
	if File_comparator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comparator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageCompareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comparator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageCompareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comparator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comparator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comparator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comparator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliverImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comparator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_comparator_proto_goTypes,
		DependencyIndexes: file_comparator_proto_depIdxs,
		MessageInfos:      file_comparator_proto_msgTypes,
	}.Build()
	File_comparator_proto = out.File
	file_comparator_proto_rawDesc = nil
	file_comparator_proto_goTypes = nil
	file_comparator_proto_depIdxs = nil
}
